services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000' # Los puertos deben estar entre comillas
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '3001:3001' # Los puertos también aquí entre comillas
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - ./.env
    command: npm run dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017' # Igualmente, comillas en los puertos
