jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t jarvis-app .

      - name: Run application with API key
        run: docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} jarvis-app npm start
